#!/bin/bash

if ps -ef | grep -v grep | grep text-example ; then
	exit 0 
else

	(while :; do cat /home/pi/ledbus/bustimes; sleep 2; done) | sudo /home/pi/ledbus/rpi-rgb-led-matrix/text-example -f /home/pi/ledbus/rpi-rgb-led-matrix/fonts/5x8.bdf -r 16 -C 0,200,0
	exit 0
fi
